version: '3'

services:
  gdsparser:
    container_name: gdsparser
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    user: $UID:$GID
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - ../:/app
      - ./run.sh:/run.sh
    environment:
      - HOME=/tmp
    entrypoint: /run.sh